(function(){
  var URL='https://liwufucwbcmrvibuhipy.supabase.co', KEY='sb_publishable_O5svMu6j-c74TGYdBXpbuA_BQYXzLGQ';
  var locked=['pi-enter-data.html','pi-tracking.html','pi-archive.html'];
  var page=(location.pathname.split('/').pop()||'index.html').toLowerCase(), privatePage=locked.indexOf(page)!==-1;
  var client=window.supabase&&window.supabase.createClient?window.supabase.createClient(URL,KEY):null;
  window.claimsSupabase=client;
  function style(){var s=document.createElement('style');s.textContent='.claims-auth-button{position:fixed;right:22px;top:20px;z-index:1000;width:42px;height:42px;border:1px solid var(--border,#d7c9af);border-radius:50%;background:var(--surface,#fff);color:var(--ink,#4a3826);font-size:19px;box-shadow:0 6px 18px rgba(0,0,0,.12)}.claims-auth-modal{position:fixed;inset:0;z-index:1100;background:rgba(30,22,15,.48);display:flex;align-items:center;justify-content:center;padding:20px}.claims-auth-card{width:min(390px,100%);border-radius:22px;background:var(--surface,#fff);color:var(--ink,#4a3826);padding:25px;box-shadow:0 20px 50px rgba(0,0,0,.25)}.claims-auth-card h2{margin:0 0 6px;font-family:Mitr,sans-serif;font-size:22px}.claims-auth-card p{margin:0 0 18px;color:var(--ink-soft,#93805f)}.claims-auth-card input{width:100%;height:44px;margin:0 0 10px;padding:0 12px;border:1px solid var(--border,#d7c9af);border-radius:12px;background:var(--bg,#fbf2e2);color:inherit;font:inherit}.claims-auth-actions{display:flex;gap:9px}.claims-auth-actions button{flex:1;border:0;border-radius:12px;padding:11px;background:var(--stamp-red,#c94f4f);color:var(--on-stamp,#fff);font:600 14px Mitr,sans-serif}.claims-auth-actions .cancel{background:transparent;color:var(--ink-soft,#93805f);border:1px solid var(--border,#d7c9af)}.claims-auth-message{min-height:20px;margin-top:12px!important;font-size:13px;color:var(--stamp-red-deep,#a83a3a)!important}.claims-private-link{display:none!important}';document.head.appendChild(s)}
  function links(show){document.querySelectorAll('a[href]').forEach(function(a){var h=a.getAttribute('href').split('?')[0].split('#')[0].toLowerCase();if(locked.indexOf(h)!==-1)a.classList.toggle('claims-private-link',!show)})}
  function dialog(){var w=document.createElement('div');w.className='claims-auth-modal';w.innerHTML='<form class="claims-auth-card"><h2>🔐 เข้าสู่ระบบ</h2><p>สำหรับจัดการข้อมูลและคลังไฟล์</p><input name="email" type="email" placeholder="อีเมล" required><input name="password" type="password" placeholder="รหัสผ่าน" required><div class="claims-auth-actions"><button type="button" class="cancel">ยกเลิก</button><button>เข้าสู่ระบบ</button></div><p class="claims-auth-message"></p></form>';document.body.appendChild(w);w.querySelector('.cancel').onclick=function(){w.remove()};w.addEventListener('click',function(e){if(e.target===w)w.remove()});w.querySelector('form').onsubmit=async function(e){e.preventDefault();var f=e.currentTarget,m=f.querySelector('.claims-auth-message');m.textContent='กำลังเข้าสู่ระบบ…';var r=await client.auth.signInWithPassword({email:f.email.value.trim(),password:f.password.value});if(r.error){m.textContent=r.error.message;return}location.href=privatePage?page:'pi-enter-data.html'}}
  async function admin(user){if(!client||!user)return false;var r=await client.from('claims_admins').select('user_id').eq('user_id',user.id).maybeSingle();return !r.error&&!!r.data}
  function button(on){var b=document.createElement('button');b.className='claims-auth-button';b.title=on?'ออกจากระบบ':'เข้าสู่ระบบ';b.setAttribute('aria-label',b.title);b.textContent=on?'↪':'🔐';b.onclick=async function(){if(!on){dialog();return}await client.auth.signOut();location.href='index.html'};document.body.appendChild(b)}
  async function start(){style();if(!client){links(false);if(privatePage)location.href='index.html';button(false);return}var session=(await client.auth.getSession()).data.session, on=session&&await admin(session.user);links(on);if(privatePage&&!on){location.href='index.html';return}button(!!on)}
  document.addEventListener('DOMContentLoaded',start);
})();
