(function(){
  var watched={pi_outbound_batches:true,pi_returns_data:true,pi_tracking_results:true};
  var nativeSet=Storage.prototype.setItem, nativeGet=Storage.prototype.getItem, queue={}, ready=false;
  function parse(v){try{return JSON.parse(v||'[]')}catch(e){return []}}
  function remember(key,value){queue[key]=value;if(ready)flush(key)}
  Storage.prototype.getItem=function(key){if(this===localStorage&&key==='pi_tracking_results'){var temp=sessionStorage.getItem(key);if(temp!==null)return temp;}return nativeGet.call(this,key)};
  Storage.prototype.setItem=function(key,value){if(this===localStorage&&watched[key]){if(key==='pi_tracking_results')sessionStorage.setItem(key,value);else nativeSet.call(this,key,value);remember(key,value);return;}return nativeSet.call(this,key,value)};
  function rows(key,value){var list=parse(value);if(key==='pi_outbound_batches')return{table:'claims_outbound',conflict:'tracking,ship_date',rows:list.map(function(x){return{tracking:x.tracking,ship_date:x.date,source_file:x.source||null}}).filter(function(x){return x.tracking&&x.ship_date})};if(key==='pi_returns_data')return{table:'claims_returns',conflict:'tracking,return_date',rows:list.map(function(x){return{tracking:x.tracking,return_date:x.date,order_no:x.order||null,product_name:x.product||null,sku:x.sku||null,quantity:Number(x.qty||1),cod_amount:Number(x.cod||0),source_file:x.source||null}}).filter(function(x){return x.tracking&&x.return_date})};if(key==='pi_tracking_results')return{table:'claims_tracking',conflict:'tracking',rows:list.map(function(x){var days=Number(x.stallDays);return{tracking:x.tracking,ship_date:x.shipDate||null,latest_status:x.status||null,last_update:x.lastUpdate||null,stalled_days:Number.isFinite(days)?days:null,outcome:days>=10?'claimable':'follow_up',source_file:x.lastSource||null,updated_at:new Date().toISOString()}}).filter(function(x){return x.tracking})}}
  async function flush(key){var client=window.claimsSupabase,value=queue[key];if(!client||value===undefined)return;var item=rows(key,value);if(!item||!item.rows.length){delete queue[key];return;}var result=await client.from(item.table).upsert(item.rows,item.conflict?{onConflict:item.conflict}:{});if(result.error){console.warn('Claims cloud sync:',result.error.message);return;}delete queue[key];window.dispatchEvent(new CustomEvent('claims-cloud-saved',{detail:{key:key,count:item.rows.length}}));}
  function syncExisting(){Object.keys(watched).forEach(function(key){var v=key==='pi_tracking_results'?sessionStorage.getItem(key)||nativeGet.call(localStorage,key):nativeGet.call(localStorage,key);if(v)remember(key,v)})}
  window.addEventListener('claims-auth-ready',function(e){ready=!!(e.detail&&e.detail.admin);if(ready)syncExisting()});
  window.claimsCloudSync=function(key){if(watched[key])remember(key,nativeGet.call(localStorage,key)||sessionStorage.getItem(key)||'[]')};
})();
